{
  "headers": {
    "client_id": "test-client-id",
    "client_secret": "test-client-secret",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.51.1",
    "accept": "*/*",
    "postman-token": "050f0261-d402-422a-89b0-12941f7a17ff",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "170"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/products",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/products",
  "listenerPath": "/api/*",
  "localAddress": "/127.0.0.1:8082",
  "relativePath": "/api/products",
  "uriParams": {},
  "rawRequestUri": "/api/products",
  "rawRequestPath": "/api/products",
  "remoteAddress": "/127.0.0.1:62582",
  "requestPath": "/api/products"
}